### PR TITLE
Update header format to latest specification

### PR DESCRIPTION
**Pull request by cvazac**
Spec changes:
- [named params](https://github.com/w3c/server-timing/commit/846745dcf4a2520086e1accfa786f713ee27876a#diff-eacf331f0ffc35d4b482f1d15a887d3b)
- [duration -> dur, description -> desc](https://github.com/w3c/server-timing/commit/c9699cb33054d9ffdaf92714a326823699872afb)

### CODE REVIEW

**Comment by tpeczek** [comment]
@cvazac thank you very much for the pull request. Is the latest specification supported in Chrome?

**Comment by cvazac** [comment]
Not until 65:
https://twitter.com/vazac/status/950433836130848768

This will be the supported format for firefox when it lands (version 60?)

**Comment by tpeczek** [comment]
Ok, I've planned the release for March 6. Thank you once again.

**Comment by cvazac** [comment]
Makes sense. 

I'm sure you know this, but up until 65, server-timing is behind [chrome://flags/#enable-experimental-web-platform-features](chrome://flags/#enable-experimental-web-platform-features). So there probably aren't a _ton_ of users quite yet.

**Comment by tpeczek** [comment]
You are right, there is only a handful, but I prefer to avoid potential confusion anyway ;).

**Pull request merged**
